#!/usr/bin/env python3
"""
Generate the SDK and schemas enum modules from one source of truth.

EventType / Severity / FailureType used to be hand-maintained twice — once in
``dunetrace.models`` (the zero-dependency SDK) and once in
``dunetrace_schemas.enums`` (pydantic-backed, used at the ingest boundary) —
because neither package may import the other. ``test_sdk_parity.py`` caught
drift after the fact. This script removes the duplication: the members live in
``packages/schemas-py/dunetrace_schemas/enum_source.py`` (plain tuples, no
Enum, no deps) and both modules are emitted from it.

    python scripts/gen_enums.py           # (re)write both generated modules
    python scripts/gen_enums.py --check   # exit 1 with a diff if either is stale

Output is deterministic and already ruff-format-clean, so no formatter needs to
be installed to run this (the docs-consistency CI job has only the SDK).

The source module is loaded by file path, not via ``import dunetrace_schemas``,
because that package's ``__init__`` imports pydantic and this script must run
with nothing but the standard library.
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import json
import pathlib
import sys
from types import ModuleType
from typing import Dict, List, Optional, Sequence, TextIO, Tuple

_REPO = pathlib.Path(__file__).resolve().parent.parent

SOURCE_REL = "packages/schemas-py/dunetrace_schemas/enum_source.py"

HEADER = (
    "# GENERATED by scripts/gen_enums.py from "
    "packages/schemas-py/dunetrace_schemas/enum_source.py — do not edit"
)

_SDK_DOCSTRING = '''"""
Wire-format enums for the Dunetrace SDK (generated).

Import these from ``dunetrace.models`` (or ``dunetrace``) — this module exists so
the SDK and ``dunetrace_schemas`` can share one definition without an import
relationship. To add or change a member, edit
``packages/schemas-py/dunetrace_schemas/enum_source.py`` and run
``python scripts/gen_enums.py``.
"""'''

_SCHEMAS_DOCSTRING = '''"""
Canonical enums for the Dunetrace wire format (generated).

These are value-for-value identical to ``dunetrace.models`` (the SDK) — both
modules are generated from ``enum_source.py`` in this package, which is the
place to edit. ``tests/test_sdk_parity.py`` remains as the backstop that
asserts the two agree; there is still no import relationship between the
packages. Regenerate with ``python scripts/gen_enums.py``.
"""'''

# rel path under the repo root -> module docstring for that target.
TARGETS: Dict[str, str] = {
    "packages/sdk-py/dunetrace/_enums.py": _SDK_DOCSTRING,
    "packages/schemas-py/dunetrace_schemas/enums.py": _SCHEMAS_DOCSTRING,
}

EnumMember = Tuple[str, str, Optional[str]]


def load_source(repo_root: pathlib.Path = _REPO) -> ModuleType:
    """Load enum_source.py by path (no package import, no pydantic)."""
    path = repo_root / SOURCE_REL
    spec = importlib.util.spec_from_file_location("_dunetrace_enum_source", path)
    if spec is None or spec.loader is None:  # pragma: no cover - importlib contract
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _validate(enums: Sequence[Tuple[str, Sequence[EnumMember]]]) -> None:
    """Refuse to emit an enum that Python would reject or that would alias silently."""
    for class_name, members in enums:
        if not members:
            raise ValueError(f"{class_name}: no members")
        seen_names: set = set()
        seen_values: set = set()
        for name, value, comment in members:
            if not name.isidentifier() or not name.isupper():
                raise ValueError(f"{class_name}.{name}: member name must be UPPER_CASE identifier")
            if name in seen_names:
                raise ValueError(f"{class_name}.{name}: duplicate member name")
            if value in seen_values:
                # A duplicate value makes Enum treat the later member as an alias
                # of the earlier one; that is never what a wire enum wants.
                raise ValueError(f"{class_name}.{name}: duplicate value {value!r}")
            if comment is not None and not comment.strip():
                raise ValueError(f"{class_name}.{name}: empty comment (use None)")
            seen_names.add(name)
            seen_values.add(value)


def render_enum(class_name: str, members: Sequence[EnumMember]) -> str:
    lines: List[str] = [f"class {class_name}(str, Enum):"]
    for name, value, comment in members:
        if comment:
            for comment_line in comment.rstrip("\n").split("\n"):
                text = comment_line.rstrip()
                lines.append(f"    # {text}" if text else "    #")
        # json.dumps, not repr(): ruff format wants double quotes, and this output
        # must be format-clean without a formatter installed.
        lines.append(f"    {name} = {json.dumps(value)}")
    return "\n".join(lines) + "\n"


def render_module(docstring: str, enums: Sequence[Tuple[str, Sequence[EnumMember]]]) -> str:
    parts = [
        HEADER + "\n",
        docstring + "\n",
        "from __future__ import annotations\n",
        "from enum import Enum\n",
    ]
    body = "\n".join(parts)
    for class_name, members in enums:
        body += "\n\n" + render_enum(class_name, members)
    return body


def render_all(repo_root: pathlib.Path = _REPO) -> Dict[str, str]:
    """Return {relative path: file text} for every generated module."""
    source = load_source(repo_root)
    enums = list(source.ENUMS)
    _validate(enums)
    return {rel: render_module(doc, enums) for rel, doc in TARGETS.items()}


def write(repo_root: pathlib.Path = _REPO) -> List[str]:
    """Write every generated module; return the relative paths that changed."""
    changed: List[str] = []
    for rel, text in render_all(repo_root).items():
        path = repo_root / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            changed.append(rel)
    return changed


def check(repo_root: pathlib.Path = _REPO, out: Optional[TextIO] = None) -> int:
    """Exit-code style: 0 when every generated module matches the source, else 1."""
    # Resolved at call time so contextlib.redirect_stdout (tests) is honoured.
    out = out if out is not None else sys.stdout
    stale: List[str] = []
    for rel, expected in render_all(repo_root).items():
        path = repo_root / rel
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        stale.append(rel)
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{rel} (on disk)",
            tofile=f"{rel} (generated)",
        )
        out.write("".join(diff))
        if not actual.endswith("\n") and actual:
            out.write("\n")
    if stale:
        out.write(
            "\nSTALE: "
            + ", ".join(stale)
            + f"\nRegenerate with: python scripts/gen_enums.py  (source: {SOURCE_REL})\n"
        )
        return 1
    out.write(f"OK: {len(TARGETS)} generated enum modules match {SOURCE_REL}\n")
    return 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 with a diff if a generated module is out of date",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check()
    changed = write()
    if changed:
        print("wrote: " + ", ".join(changed))
    else:
        print(f"up to date: {', '.join(TARGETS)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
